server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${SPC_DB_USER:-root}
  password: ${SPC_DB_PASSWORD:-root}
  url: ${SPC_DB_URL:-jdbc:mysql://localhost:3306/theta_db}
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect